```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
source(here::here("R", "packages.R"))
```

# KẾT QUẢ NGHIÊN CỨU
ddddddd

## Đặc điểm đối tượng nghiên cứu
gg

### Đặc điểm theo tuổi và giới tính

### Đặc điểm theo hoàn cảnh gia đình, nghề nghiệp, hôn nhân

###1.3 Đặc điểm thời gian mắc bệnh

###1.4 Đặc điểm yếu tố thúc đẩy bệnh

###1.5 Đặc điểm tính chất xuất hiện bệnh 3.1.6 Điểm PSQI lúc khởi trị

##2 Đánh giá hiệu quả điều trị

###2.1 Hiệu quả cải thiện thời lượng giấc ngủ

###2.2 Hiệu quả cải thiện thời gian vào giấc ngủ

###2.3 Tác dụng cải thiện hiệu quả giấc ngủ

###2.4 Hiệu quả cải thiện chất lượng giấc ngủ

###2.5 Hiệu quả cải thiện thang điểm PSQI

###2.6 Hiệu quả cải thiện một số triệu chứng thứ phát sau mất ngủ

###2.7 Hiệu quả cải thiện một số triệu chứng YHCT

##3. Một số yếu tố liên quan đến kết quả điều trị

#Chương IV: BÀN LUẬN

##1 Đặc điểm chung của đối tượng nghiên cứu

###1.1 Phân bố bệnh nhân theo tuổi

###1.2 Phân bố bệnh nhân theo giới tính

###1.3 Phân bố bệnh nhân theo nghề nghiệp

###1.4 Phân bố bệnh nhân theo tình trạng hôn nhân

###1.5 Phân bố bệnh nhân theo hoàn cảnh gia đình

###1.5 Phân bố thời gian mắc bệnh của bệnh nhân

###1.6 Phân bố theo yếu tố thúc đẩy

###1.7 Phân bố theo tính chất xuất hiện bệnh

###1.8 Điểm PSQI trước khi điều trị

##2. Hiệu quả của phương pháp điều trị

